name: build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Build Busybox
        run:  wget https://github.com/busytex/busyfs/releases/download/data/busytex https://github.com/busytex/busyfs/releases/download/data/texlive-basic.tar.gz && make -j2 busybox && ./build/busybox && cc -shared -fPIC log_file_access_dynamic.c -o log_file_access_dynamic.so -ldl
      
      - name: Test Busybox
        run: |
            chmod +x busytex
            mkdir dist-native
            tar -xf texlive-basic.tar.gz
            mv build/texlive-basic dist-native/texlive
            python packfs.py -i dist-native -o packfs.h
            cc -shared -fPIC packfs.c -o packfs.so -ldl @packfs.h.txt
            
            #LD_PRELOAD=$PWD/log_file_access_dynamic.so ./build/busybox cat dist-native/LICENSE.CTAN
            #strace -e trace=file,read,write,close -f ./build/busybox cat dist-native/LICENSE.CTAN
            #LD_PRELOAD=$PWD/packfs.so ./build/busybox cat build/texlive-basic/LICENSE.CTAN

            export DIST=$PWD/dist-native
            cd example
            mv ../dist-native .
            export DIST=dist-native
            export PDFLATEXFMT=$DIST/texlive/texmf-dist/texmf-var/web2c/pdftex/pdflatex.fmt
            export BUSYTEX=../busytex
            export TEXMFDIST=$DIST/texlive/texmf-dist
            export TEXMFVAR=$DIST/texlive/texmf-dist/texmf-var
            export TEXMFCNF=$TEXMFDIST/web2c
            export FONTCONFIG_PATH=$DIST
            ##echo LOG_FILE_ACCESS
            ls $DIST
            LD_PRELOAD=$PWD/../packfs.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            #LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex 
            #echo STRACE
            #strace -f -e trace=file,read,write,close      $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            
            LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX bibtex8 --8bit example.aux
            LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            #ls example.pdf
            #ls -lah log_file_access_dynamic.so
            #nm log_file_access_dynamic.so
            #LD_PRELOAD=$PWD/log_file_access_dynamic.so /usr/bin/cat Makefile
            #nm -u ./build/busybox
            #LD_PRELOAD=$PWD/log_file_access_dynamic.so ./build/busybox cat Makefile
            #strace -f ./build/busybox cat Makefile
            #LD_PRELOAD=log_file_access_dynamic.so ./build/busybox ls

      - uses: actions/upload-artifact@v4
        with:
          name: build
          #path: build
          path: |
            packfs.h
            packfs.h.txt
            example/example.pdf
