name: build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Build Busybox
        run:  wget https://github.com/busytex/busyfs/releases/download/data/busytex https://github.com/busytex/busyfs/releases/download/data/texlive-basic.tar.gz && make -j2 busybox && ./build/busybox && cc -shared -fPIC log_file_access_dynamic.c -o log_file_access_dynamic.so -ldl
      
      - name: Test Busybox
        run: |
            mkdir dist-native
            mv busytex dist-native && chmod +x dist-native/busytex
            tar -xf texlive-basic.tar.gz
            cp -r build/texlive-basic dist-native/texlive
            cp build/texlive-basic/texmf-dist/texmf-var/web2c/pdftex/pdflatex.fmt dist-native
            python packfs.py -i build/texlive-basic -o build/packfs.c
            cc build/packfs.c -o build/packfs -ldl @build/packfs.c.txt
            ./build/packfs build/texlive-basic/LICENSE.CTAN

            #export DIST=$PWD/dist-native
            #export PDFLATEXFMT=$DIST/pdflatex.fmt
            #export BUSYTEX=$DIST/busytex
            #export TEXMFDIST=$DIST/texlive/texmf-dist
            #export TEXMFVAR=$DIST/texlive/texmf-dist/texmf-var
            #export TEXMFCNF=$TEXMFDIST/web2c
            #export FONTCONFIG_PATH=$DIST
            #cd example
            #echo LOG_FILE_ACCESS
            #LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            #echo STRACE
            #strace -f -e trace=file                       $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            
            #LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX bibtex8 --8bit example.aux
            #LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            #LD_PRELOAD=$PWD/../log_file_access_dynamic.so $BUSYTEX pdflatex --no-shell-escape --interaction nonstopmode --halt-on-error --output-format=pdf --fmt $PDFLATEXFMT example.tex
            #ls example.pdf
            #ls -lah log_file_access_dynamic.so
            #nm log_file_access_dynamic.so
            #LD_PRELOAD=$PWD/log_file_access_dynamic.so /usr/bin/cat Makefile
            #nm -u ./build/busybox
            #LD_PRELOAD=$PWD/log_file_access_dynamic.so ./build/busybox cat Makefile
            #strace -f ./build/busybox cat Makefile
            #LD_PRELOAD=log_file_access_dynamic.so ./build/busybox ls

      - uses: actions/upload-artifact@v4
        with:
          name: build
          #path: build
          path: |
            build/packfs.c
            build/packfs.c.txt
            build/packfs
