name: build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Build Busybox
        run: make -j2 busybox
      
      - name: Test Busybox
        run: ./build/busybox ls && ./build/busybox cat Makefile

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
