name: build

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Busybox
        run: make -j2 busybox

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
